### ISSUE TITLE
获取slb 的Metric数据

### ISSUE THREAD

**Issue by songcser** [aliyun/aliyun-openapi-java-sdk#1]
在获取slb的监控数据时，{instanceId:'"+instanceId+"'}设置slb的id，但是获取不到数据。ECS可以获取到。

**Comment by Brigitte1103** [comment]
上一版本可以用自己的域名在线看图片,新版本用同样的域名只能下载

**Comment by ElaineFei** [comment]
您好，很抱歉当时没能及时回复您的问题，后续阿里云官方技术人员将为您提供高效的支持。若您仍有问题未能得到解答，请您重新提交issue。感谢您关注阿里云，关注阿里云 SDK。
