### ISSUE TITLE
ocs 的sdk用不了

### ISSUE THREAD

**Issue by chenshun00** [aliyun/aliyun-openapi-java-sdk#108]
![image](https://user-images.githubusercontent.com/26037282/51008825-66721980-1588-11e9-8119-a18586aa4b7f.png)

能找到 `xxxx.xxx.xxx.xxx.ocs.aliyuncs.com` , 但是response中说没有，实际dubug是存在的。
找不到最新的 `xx-xxxxxx.memcache.rds.aliyuncs` 的memcache.,

**Comment by JacksonTian** [comment]
1 个 request 尽量只用一次。

**Comment by chenshun00** [comment]
被改成 kv-store了
