### ISSUE TITLE
请问有在java中如何调用接口发送短信的例子吗？

### ISSUE THREAD

**Issue by IceBergHu** [aliyun/aliyun-openapi-java-sdk#11]
请问有在java中如何调用接口发送短信的例子吗？java-jdk中不大会用，不知道怎么准备参数、调用接口

**Comment by ElaineFei** [comment]
您好，很抱歉当时没能及时回复您的问题，后续阿里云官方技术人员将为您提供高效的支持。若您仍有问题未能得到解答，请您重新提交issue。感谢您关注阿里云，关注阿里云 SDK。
