### ISSUE TITLE
如何获取所有区域的信息

### ISSUE THREAD

**Issue by xhrwp** [aliyun/aliyun-openapi-java-sdk#13]
创建IClientProfile profile对象的时候只能DefaultProfile.getProfile方法获取，但是需要传入一个regionId。当我是查询所有区域的时候，这个regionId传递什么值呢？

**Comment by ElaineFei** [comment]
您好，很抱歉当时没能及时回复您的问题，后续阿里云官方技术人员将为您提供高效的支持。若您仍有问题未能得到解答，请您重新提交issue。感谢您关注阿里云，关注阿里云 SDK。
