### ISSUE TITLE
邮件发送报错

### ISSUE THREAD

**Issue by ProgrammerAllen** [aliyun/aliyun-openapi-java-sdk#135]
调用发送邮件sdk（aliyun-java-sdk-dm）报错，Could not connect to SMTP host: smtp.exmail.qq.com, port: 465, response: -1，调用sdk中MailSender.sendMail方法，百度提示需要在Properties添加p.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");但是MailSender类中Properties只有固定的3个属性添加，请问是我调用问题还是？

**Comment by JacksonTian** [comment]
Please provide more detail. How to reproduce it.

**Comment by ProgrammerAllen** [comment]
String host = "smtp.exmail.qq.com";
		String port = "465";
		String userName = "notification@cnaac.org.cn";
		String password = "XXX";
		String aliFrom = "notification@cnaac.org.cn";
		String title = "XXX";
		List<Email.Address> recipients = new ArrayList<Email.Address>();
		recipients.add(new Email.Address("zuolunwen@xycloud.vip", ""));
		MailSender aliMailSender = new MailSender(host, port, userName, password);

		Email email = Email.builder()
				.from(aliFrom, title)
				.recipients(recipients)
				.subject("邮箱验证码")
				.textHTML("test")
				.replyToAddress(new Email.Address(aliFrom, ""))
				.build();
		String result = aliMailSender.sendMail(email);

**Comment by JacksonTian** [comment]
请根据文档：https://help.aliyun.com/document_detail/29450.html 来做下修正。

**Comment by ssy352959096** [comment]
您好,问题是否已经得到解决,如果已经解决,稍后我们将会关闭这个问题.感谢您的支持!
