### ISSUE TITLE
阿里云短信新版本接口SDK

### ISSUE THREAD

**Issue by jsyzthz** [aliyun/aliyun-openapi-java-sdk#145]
看了下官方文档有个新版本的接口只依赖core，也就是说aliyun-java-sdk-dysmsapi这个不需要了？

**Comment by dashdots** [comment]
不需要了，就依赖core，使用API Explorer生成的demo就可以用

**Comment by hzdjulytech** [comment]
新版的对参数的封装没有 aliyun-java-sdk-dysmsapi 友好
引入 aliyun-java-sdk-dysmsapi 用不过时的方法会报错
![image](https://user-images.githubusercontent.com/36155555/71616999-f83cc180-2bf3-11ea-8848-fae62b29bc20.png)

 DefaultProfile.addEndpoint("cn-hangzhou", product, "cn-hangzhou");
			//DefaultProfile.addEndpoint("cn-hangzhou", "cn-hangzhou", product, "dysmsapi.aliyuncs.com");
