### ISSUE TITLE
最新版的TextAntispamDetectionRequest怎么使用啊？

### ISSUE THREAD

**Issue by passerbya** [aliyun/aliyun-openapi-java-sdk#17]
官网上的demo（https://help.aliyun.com/document_detail/28441.html）是10月18号的，里面的代码已经不适合v20161206 API了

**Comment by ElaineFei** [comment]
您好，很抱歉当时没能及时回复您的问题，后续阿里云官方技术人员将为您提供高效的支持。若您仍有问题未能得到解答，请您重新提交issue。感谢您关注阿里云，关注阿里云 SDK。
