### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/http/ssl/TrustStrategy

### ISSUE THREAD

**Issue by DanRui** [aliyun/aliyun-openapi-java-sdk#180]
* **Product and API**: java-sdk-core
* **Platform**: java
* **Mininum Code**: 4.3.5

![微信图片_20190312165753](https://user-images.githubusercontent.com/13469589/54187213-fdefdc00-44e7-11e9-9da6-fcd6268aebcb.png)

使用的最新版java sdk core，初始化方法报错，去除了httpclient包还是一样的。

**Comment by ssy352959096** [comment]
你好，我们需要更多的使用信息，以便找出问题，请先加入我们钉钉群23133418，感谢你的反馈！

**Comment by JacksonTian** [comment]
这个问题可能是由于某些 maven 安装依赖的时候不完全导致的。请你在自己的项目中添加如下的依赖：

```xml
<dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
            <version>4.5.7</version>
        </dependency>
```

**Comment by JacksonTian** [comment]
另一种可能是包冲突导致的。请参考 https://blog.csdn.net/u014079773/article/details/66973284 或者 https://blog.csdn.net/u012561176/article/details/78871652 解决。

**Comment by DanRui** [comment]
<dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpcore</artifactId>
            <version>4.4</version>
        </dependency>

        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.8.5</version>
        </dependency>
添加这两个依赖后可以跑了。

**Comment by JacksonTian** [comment]
@DanRui 感谢你的反馈。
