### ISSUE TITLE
关于CreateNatGatewayRequest中缺少Spec的设置

### ISSUE THREAD

**Issue by kai8406** [aliyun/aliyun-openapi-java-sdk#20]
你好,在阿里云官网的API文档及OpenAPI Explorer中可以看到有Spec的设置,但是在SDK中缺少这个参数.因此无法指定nat网关的规格.

**Comment by ElaineFei** [comment]
您好，该问题属于产品范畴，您可以提工单直接联系产品。或者加入钉钉群 11771185，方便我们为您寻找产品的support，在git里面不是很方便，望您理解。

**Comment by gaort** [comment]
@kai8406 建议您提交NAT网关的工单，可以更快的得到回复以及处理 😄
