### ISSUE TITLE
短信发送调用超时

### ISSUE THREAD

**Issue by nevermorecc** [aliyun/aliyun-openapi-java-sdk#201]
短信发送，版本 aliyun-java-sdk-core 4.0.3，请问这个问题怎么解决
SDK.ServerUnreachable : Server unreachable: java.net.ConnectException: Connection timed out (Connection timed out)

**Comment by ssy352959096** [comment]
您好，建议您尝试以下操作；
1.  检查服务端是否正常；
2.  如果服务端没有问题，先将版本升级至4.3.7，设置超时时间；参考文档 https://github.com/aliyun/aliyun-openapi-java-sdk/blob/master/README_zh.md#%E8%B6%85%E6%97%B6%E6%9C%BA%E5%88%B6；
