### ISSUE TITLE
最新的4.3.x版本的SDK有问题。。。

### ISSUE THREAD

**Issue by lan149** [aliyun/aliyun-openapi-java-sdk#204]
从console里面直接截出来的，里面涉及私密信息已经被我用“HIDDENHIDDENHIDDEN”替换了。昨天试的好像是4.3.5，今天看4.3.6也出来了，都是一个问题：

10:53:23.935 [main] DEBUG org.apache.http.client.protocol.RequestAddCookies - CookieSpec selected: default
10:53:23.993 [main] DEBUG org.apache.http.client.protocol.RequestAuthCache - Auth cache not set in the context
10:53:23.998 [main] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection request: [route: {s}->https://dysmsapi.aliyuncs.com:443][total kept alive: 0; route allocated: 0 of 5; total allocated: 0 of 64]
10:53:24.086 [main] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection leased: [id: 0][route: {s}->https://dysmsapi.aliyuncs.com:443][total kept alive: 0; route allocated: 1 of 5; total allocated: 1 of 64]
10:53:24.114 [main] DEBUG org.apache.http.impl.execchain.MainClientExec - Opening connection {s}->https://dysmsapi.aliyuncs.com:443
10:53:25.906 [main] DEBUG org.apache.http.impl.conn.DefaultHttpClientConnectionOperator - Connecting to dysmsapi.aliyuncs.com/106.11.45.35:443
10:53:25.906 [main] DEBUG org.apache.http.conn.ssl.SSLConnectionSocketFactory - Connecting socket to dysmsapi.aliyuncs.com/106.11.45.35:443 with timeout 5000
10:53:27.781 [main] DEBUG org.apache.http.conn.ssl.SSLConnectionSocketFactory - Enabled protocols: [TLSv1, TLSv1.1, TLSv1.2]
10:53:27.781 [main] DEBUG org.apache.http.conn.ssl.SSLConnectionSocketFactory - Enabled cipher suites:[TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384, TLS_DHE_RSA_WITH_AES_256_GCM_SHA384, TLS_DHE_DSS_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_DSS_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, TLS_RSA_WITH_AES_256_CBC_SHA256, TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384, TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384, TLS_DHE_RSA_WITH_AES_256_CBC_SHA256, TLS_DHE_DSS_WITH_AES_256_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDH_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_DSS_WITH_AES_256_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA256, TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_DSS_WITH_AES_128_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDH_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_DSS_WITH_AES_128_CBC_SHA, TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA, SSL_RSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA, SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA, SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA, TLS_EMPTY_RENEGOTIATION_INFO_SCSV]
10:53:27.782 [main] DEBUG org.apache.http.conn.ssl.SSLConnectionSocketFactory - Starting handshake
10:53:29.043 [main] DEBUG org.apache.http.conn.ssl.SSLConnectionSocketFactory - Secure session established
10:53:29.043 [main] DEBUG org.apache.http.conn.ssl.SSLConnectionSocketFactory -  negotiated protocol: TLSv1.2
10:53:29.043 [main] DEBUG org.apache.http.conn.ssl.SSLConnectionSocketFactory -  negotiated cipher suite: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
10:53:29.045 [main] DEBUG org.apache.http.conn.ssl.SSLConnectionSocketFactory -  peer principal: CN=*.aliyuncs.com, O="Alibaba (China) Technology Co., Ltd.", L=HangZhou, ST=ZheJiang, C=CN
10:53:29.045 [main] DEBUG org.apache.http.conn.ssl.SSLConnectionSocketFactory -  peer alternative names: [*.aliyuncs.com, *.cn-shenzhen-finance-1.aliyuncs.com, *.cn-sichuan.aliyuncs.com, *.jp-fudao.aliyuncs.com, *.ap-south-1.aliyuncs.com, *.cn-huhehaote.aliyuncs.com, *.cn-chengdu.aliyuncs.com, *.ap-southeast-1.aliyuncs.com, *.in-mumbai.aliyuncs.com, *.cn-hangzhou.aliyuncs.com, *.tw-gaoxiong.aliyuncs.com, *.cn-guizhou.aliyuncs.com, *.cn-hangzhou-finance.aliyuncs.com, *.cn-north-2-gov-1.aliyuncs.com, *.cn-qingdao.aliyuncs.com, *.me-east-1.aliyuncs.com, *.eu-central-1.aliyuncs.com, *.cn-shenzhen.aliyuncs.com, *.us-east-1.aliyuncs.com, *.us-west-1.aliyuncs.com, *.cn-zhangjiakou.aliyuncs.com, *.cn-beijing.aliyuncs.com, *.ap-southeast-2.aliyuncs.com, *.eu-west-1.aliyuncs.com, *.cn-ningxia.aliyuncs.com, *.cn-hongkong.aliyuncs.com, *.ap-southeast-3.aliyuncs.com, *.ap-southeast-5.aliyuncs.com, *.cn-shanghai.aliyuncs.com, *.cn-qingdao-nebula.aliyuncs.com, *.cn-shanghai-finance-1.aliyuncs.com, *.ap-northeast-1.aliyuncs.com, *.cn-shenzhen-cloudstone.aliyuncs.com, *.cn-haidian.aliyuncs.com, aliyuncs.com]
10:53:29.045 [main] DEBUG org.apache.http.conn.ssl.SSLConnectionSocketFactory -  issuer principal: CN=GlobalSign Organization Validation CA - SHA256 - G2, O=GlobalSign nv-sa, C=BE
10:53:29.046 [main] DEBUG org.apache.http.impl.conn.DefaultHttpClientConnectionOperator - Connection established 192.168.8.60:50955<->106.11.45.35:443
10:53:29.047 [main] DEBUG org.apache.http.impl.conn.DefaultManagedHttpClientConnection - http-outgoing-0: set socket timeout to 10000
10:53:29.047 [main] DEBUG org.apache.http.impl.execchain.MainClientExec - Executing request POST /?PhoneNumbers=18812345678&Action=SendSms&Timestamp=2019-03-21T02%3A53%3A23Z&SignName=%E8%81%94%E9%BE%99%E5%8D%9A%E9%80%9AAIMO&TemplateCode=HIDDENHIDDENHIDDEN&SignatureVersion=1.0&Format=JSON&SignatureNonce=3280c6b1-068f-443d-8cbb-a55136d820a815531368037141&Version=2017-05-25&AccessKeyId=HIDDENHIDDENHIDDEN&Signature=0t1N02jTKMvzmNk7wjjWe4GmP%2Bc%3D&SignatureMethod=HMAC-SHA1&TemplateParam=%7B%22code%22%3A%22698848%22%7D&RegionId=default HTTP/1.1
10:53:29.047 [main] DEBUG org.apache.http.impl.execchain.MainClientExec - Target auth state: UNCHALLENGED
10:53:29.048 [main] DEBUG org.apache.http.impl.execchain.MainClientExec - Proxy auth state: UNCHALLENGED
10:53:29.050 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> POST /?PhoneNumbers=18812345678&Action=SendSms&Timestamp=2019-03-21T02%3A53%3A23Z&SignName=%E8%81%94%E9%BE%99%E5%8D%9A%E9%80%9AAIMO&TemplateCode=HIDDENHIDDENHIDDEN&SignatureVersion=1.0&Format=JSON&SignatureNonce=3280c6b1-068f-443d-8cbb-a55136d820a815531368037141&Version=2017-05-25&AccessKeyId=HIDDENHIDDENHIDDEN&Signature=0t1N02jTKMvzmNk7wjjWe4GmP%2Bc%3D&SignatureMethod=HMAC-SHA1&TemplateParam=%7B%22code%22%3A%22698848%22%7D&RegionId=default HTTP/1.1
10:53:29.050 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Accept-Encoding: identity
10:53:29.050 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> x-sdk-invoke-type: common
10:53:29.050 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Accept: application/json
10:53:29.051 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> x-sdk-client: Java/2.0.0
10:53:29.051 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> User-Agent: AlibabaCloud (Windows 10; amd64) Java/10+46 aliyun-java-sdk-core/4.3.6 HTTPClient/ApacheHttpClient
10:53:29.051 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Content-Type: application/x-www-form-urlencoded
10:53:29.051 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Transfer-Encoding: chunked
10:53:29.051 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Host: dysmsapi.aliyuncs.com
10:53:29.051 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Connection: Keep-Alive
10:53:29.052 [main] DEBUG org.apache.http.impl.conn.DefaultManagedHttpClientConnection - http-outgoing-0: Close connection
10:53:29.052 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "POST /?PhoneNumbers=18812345678&Action=SendSms&Timestamp=2019-03-21T02%3A53%3A23Z&SignName=%E8%81%94%E9%BE%99%E5%8D%9A%E9%80%9AAIMO&TemplateCode=HIDDENHIDDENHIDDEN&SignatureVersion=1.0&Format=JSON&SignatureNonce=3280c6b1-068f-443d-8cbb-a55136d820a815531368037141&Version=2017-05-25&AccessKeyId=HIDDENHIDDENHIDDEN&Signature=0t1N02jTKMvzmNk7wjjWe4GmP%2Bc%3D&SignatureMethod=HMAC-SHA1&TemplateParam=%7B%22code%22%3A%22698848%22%7D&RegionId=default HTTP/1.1[\r][\n]"
10:53:29.052 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Accept-Encoding: identity[\r][\n]"
10:53:29.052 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "x-sdk-invoke-type: common[\r][\n]"
10:53:29.052 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Accept: application/json[\r][\n]"
10:53:29.052 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "x-sdk-client: Java/2.0.0[\r][\n]"
10:53:29.052 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "User-Agent: AlibabaCloud (Windows 10; amd64) Java/10+46 aliyun-java-sdk-core/4.3.6 HTTPClient/ApacheHttpClient[\r][\n]"
10:53:29.053 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Content-Type: application/x-www-form-urlencoded[\r][\n]"
10:53:29.053 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Transfer-Encoding: chunked[\r][\n]"
10:53:29.053 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Host: dysmsapi.aliyuncs.com[\r][\n]"
10:53:29.053 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
10:53:29.053 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "[\r][\n]"
10:53:29.055 [main] DEBUG org.apache.http.impl.conn.DefaultManagedHttpClientConnection - http-outgoing-0: Shutdown connection
10:53:29.056 [main] DEBUG org.apache.http.impl.execchain.MainClientExec - Connection discarded
10:53:29.056 [main] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection released: [id: 0][route: {s}->https://dysmsapi.aliyuncs.com:443][total kept alive: 0; route allocated: 0 of 5; total allocated: 0 of 64]
java.lang.IllegalStateException: Content has not been provided
	at org.apache.http.util.Asserts.check(Asserts.java:34)
	at org.apache.http.entity.BasicHttpEntity.getContent(BasicHttpEntity.java:75)
	at org.apache.http.entity.BasicHttpEntity.writeTo(BasicHttpEntity.java:112)
	at org.apache.http.impl.execchain.RequestEntityProxy.writeTo(RequestEntityProxy.java:121)
	at org.apache.http.impl.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:156)
	at org.apache.http.impl.conn.CPoolProxy.sendRequestEntity(CPoolProxy.java:160)
	at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:238)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at com.aliyuncs.http.clients.ApacheHttpClient.syncInvoke(ApacheHttpClient.java:254)
	at com.aliyuncs.DefaultAcsClient.doAction(DefaultAcsClient.java:258)
	at com.aliyuncs.DefaultAcsClient.doAction(DefaultAcsClient.java:186)
	at com.aliyuncs.DefaultAcsClient.doAction(DefaultAcsClient.java:79)
	at com.aliyuncs.DefaultAcsClient.getCommonResponse(DefaultAcsClient.java:146)
	at com.chinamworld.aimo.platform.component.sms.SMSComponent.main(SMSComponent.java:50)

**Comment by JacksonTian** [comment]
亲 是 Content has not bean provided 问题吗。能否提交下详细的错误堆栈。

**Comment by lan149** [comment]
> 亲 是 Content has not bean provided 问题吗。能否提交下详细的错误堆栈。

刚刚手快了，还没有编辑完，就按Enter了，就是你说的那个问题，上面已经补偿堆栈信息了。

**Comment by JacksonTian** [comment]
好的。谢谢反馈。我们今天会发出新的修复版本。

**Comment by JacksonTian** [comment]
新的版本已经发布，大概下午会出现在 maven 中央仓库。

**Comment by JacksonTian** [comment]
4.3.7
