### ISSUE TITLE
版本依赖问题

### ISSUE THREAD

**Issue by odirus** [aliyun/aliyun-openapi-java-sdk#21]
请问 aliyun-java-sdk-core 3.* 是向下兼容 aliyun-java-sdk-core 2.* 的吗？

我们公司某个项目同时使用了短信功能和邮件功能，但是短信和邮件 SDK 分别依赖于 aliyun-java-sdk-core 3.* 2.* 两个不同的大版本。。。

**Comment by gaort** [comment]
@odirus 
您好，大版本不同的情况下，是不会向下兼容的
您的情况，有两种解决方法：
1. 如果您使用的各产品SDK(core以外)的最后commit注释结构为“XX发起的XXX自动发布……”，则可以直接排除其依赖的core包，统一使用3.X版本的core包
2. 其他情况，您可以考虑使用CommonApi，无需再添加各产品SDK的依赖
    https://help.aliyun.com/document_detail/61469.html?spm=5176.doc52740.6.544.HFYyNM
