### ISSUE TITLE
优化依赖

### ISSUE THREAD

**Issue by cn-src** [aliyun/aliyun-openapi-java-sdk#212]
* **产品和接口**:
aliyun-java-sdk-core
* **平台**:
4.3.8
* **最小代码**:
能否对依赖优化下？
1. 不知道为什么会需要 org.jacoco.agent 这个依赖
2. activation 一定是必须的么？不用邮件呢？
3. init4j 不用 init 配置呢？
4. gson 和 jaxb 等等，按我的理解 aliyun-java-sdk-core 不应该是一个通用的 http client 么？只不过内部封装了阿里的一些接口地址，签名等，为什么会跟具体的数据格式挂钩呢。如果不得不用，是否可以提供分离的模块等等方式优化依赖。比如我不需要用 xml，或者jdk自带的jaxb就可以了等等。

另：
1. 是否考虑用 OpenFeign 来作为 http client 呢？
2. 后续是否会有细化到具体产品的领域模型 API 提供，比如 sms 不在使用 CommonRequest 而是具体的 javabean 。

**Comment by cn-src** [comment]
ps: aliyun 还是 alicloud 呢？:blush:

**Comment by sjj3086786** [comment]
感谢您的反馈@cn-src 
1. 关于org.jacoco.agent这个依赖，是为了纠正被powermock忽略掉的code converage，请参考 [该文档](https://github.com/powermock/powermock/wiki/Code-coverage-with-JaCoCo)
2. activation确实是一个Unused declared dependencies，我们会进行优化，感谢！
3. ini4j的作用是读取用户自定义的配置，目前工程中会读取证书链的配置文件，请参考我们的readme [相关部分](https://github.com/aliyun/aliyun-openapi-java-sdk#use-the-default-credential-provider-chain)
4. 由于历史原因，目前阿里云的sdk会依赖core中的反序列化功能，该功能的分离是一个优化点，感谢建议！
5. 关于OpenFeign，目前core默认的http client是Apache Http Client，也允许用户注入自定义的httpclient（通过HttpClientConfig），由于http client并不会直接暴露给用户，基本不会对用户的使用体验造成影响，所以我们在短期内不会将Apache（久经考验的http client)切到更新的http client
6. 关于CommonRequest确实是一个让人诟病的设计，目前我们也正在孵化新的sdk方案，再次感谢你的反馈！

**Comment by cn-src** [comment]
1. `org.jacoco.agent` 不应该只是测试的时候才会需要么？但目前却是 runtime 的。
2. ini4j 我觉得可以采用非硬编码的方式进行解耦，比如 Class.forName 判断，spring 就有很多类似做法。

**Comment by sjj3086786** [comment]
@cn-src 
1. 我们采用`org.jacoco.agent`的offline方式来纠正被powermock破坏掉的code coverage。
大致原理如下：
- 在.java编译为.class之后的process class阶段，`org.jacoco.agent`以javaagent（**runtime**)的方式介入增强字节码，主要就是各种埋点用于计算code coverage，然后用新的.class替换老的.class存放到磁盘上，在test阶段，powermock会去读取磁盘上的.class进行mock，这里面的矛盾点在于powermock只读取磁盘上（而不是内存）的.class进行mock
2. 关于ini4j的建议我们会进行评估，看需不需要投入人力进行优化，感谢你的建议！
