### ISSUE TITLE
API changes review for Aliyun Java Sdk Core

### ISSUE THREAD

**Issue by lvc** [aliyun/aliyun-openapi-java-sdk#25]
The review of API changes for the Aliyun Java Sdk Core library since 2.1.0 version: https://abi-laboratory.pro/java/tracker/timeline/aliyun-java-sdk-core/

The report is updated three times a week. Hope it will be helpful for users and maintainers of the library.

The report is generated by https://github.com/lvc/japi-tracker and https://github.com/lvc/japi-compliance-checker tools.

Thank you.

![aliyun-java-sdk-core-1](https://user-images.githubusercontent.com/1517837/29457417-229b674c-842b-11e7-8890-844892c6e6be.png)
![aliyun-java-sdk-core-2](https://user-images.githubusercontent.com/1517837/29457421-26d2cc7e-842b-11e7-9ce2-8e7a7a850b6e.png)

**Comment by ElaineFei** [comment]
Thanks for your contribution, thank you.
