### ISSUE TITLE
aliyun-openapi-java-sdk 3.7.4 AddLivePullStreamInfoConfigRequest 不存在

### ISSUE THREAD

**Issue by zhangqianliang** [aliyun/aliyun-openapi-java-sdk#266]
* **产品和接口**:视频直播AddLivePullStreamInfoConfigRequest
* **平台**:java
* **最小代码**: AddLivePullStreamInfoConfigRequest 从3.6.0升级到3.7.4后不存在

**Comment by atptro** [comment]
您好！这可能是视频直播这块业务做了更改，建议直接去找视频直播业务的技术支持
