### ISSUE TITLE
Exception when creating sample request

### ISSUE THREAD

**Issue by liviu-graur** [aliyun/aliyun-openapi-java-sdk#280]
* **Product and API**: aliyun-java-sdk-core 4.4.0, aliyun-java-sdk-ecs 4.16.11
* **Platform**: Java
* **Mininum Code**:
```
    DefaultProfile profile = DefaultProfile.getProfile(
                "*****",                     
                "*****",            
                "*****");       
        IAcsClient client = new DefaultAcsClient(profile);
        StopInstanceRequest stopInstanceRequest = new StopInstanceRequest();
        stopInstanceRequest.setInstanceId("*****");
        stopInstanceRequest.setAcceptFormat(FormatType.JSON);
        StopInstanceResponse response = client.getAcsResponse(stopInstanceRequest);
        System.out.println(response);
```
When executing this sample code using the aliyun-java-sdk-core 4.4.0, aliyun-java-sdk-ecs 4.16.11 Java SDK version I have the following issue:

> Exception in thread "main" java.lang.IllegalStateException: Server response has a bad format type: RAW
> 	at com.aliyuncs.reader.ReaderFactory.createInstance(ReaderFactory.java:16)
> 	at com.aliyuncs.DefaultAcsClient.readResponse(DefaultAcsClient.java:314)
> 	at com.aliyuncs.DefaultAcsClient.parseAcsResponse(DefaultAcsClient.java:199)
> 	at com.aliyuncs.DefaultAcsClient.getAcsResponse(DefaultAcsClient.java:115)

Using  aliyun-java-sdk-core 4.0.3, aliyun-java-sdk-ecs 4.9.4 request works, so I think this is an issue on Alibaba SDK.

**Comment by ssy352959096** [comment]
hi, we have not reproduced your problem, you can try to upgrade the version of aliyun-java-sdk-core 4.4.2, aliyun-java-sdk-ecs 4.17.0, if the problem is not solved, you can open this question again.
Thanks for your feedback!
