### ISSUE TITLE
import com.aliyuncs.saf.model.v20180919.ExecuteRequestResponse;

### ISSUE THREAD

**Issue by bxhxnon** [aliyun/aliyun-openapi-java-sdk#289]
找不到这个包啊。按照你们官网的开发文档，导入不进来啊

**Comment by ssy352959096** [comment]
您好，请问您是否添加了产品依赖，如下：
` <dependency>
            <groupId>com.aliyun</groupId>
            <artifactId>aliyun-java-sdk-core</artifactId>
            <version>4.4.2</version>
   </dependency>
   <dependency>
            <groupId>com.aliyun</groupId>
            <artifactId>aliyun-java-sdk-saf</artifactId>
            <version>1.0.2</version>
  </dependency>`
如果问题没有解决，欢迎您再次反馈！

**Comment by bxhxnon** [comment]
依赖了啊
dependency>
        <groupId>com.aliyun</groupId>
        <artifactId>aliyun-java-sdk-saf</artifactId>
        <version>1.0.2</version>
    </dependency>


    
    <dependency>
        <groupId>com.aliyun</groupId>
        <artifactId>aliyun-java-sdk-core</artifactId>
        <optional>true</optional>
        <version>4.1.1</version>
    </dependency>还是不行 找不到

**Comment by ssy352959096** [comment]
请问您能在工程中成功添加上述两个依赖吗?

**Comment by bxhxnon** [comment]
绝对添加了....

**Comment by bxhxnon** [comment]
<dependency>
			<groupId>com.aliyun</groupId>
			<artifactId>aliyun-java-sdk-saf</artifactId>
			<version>1.0.2</version>
		</dependency>
是否还需要这个依赖？

**Comment by bxhxnon** [comment]
需要这个是否
<dependency>
			<groupId>com.aliyun</groupId>
			<artifactId>aliyun-java-sdk-saf</artifactId>
			<version>1.0.2</version>
		</dependency>

**Comment by ssy352959096** [comment]
您好，是需要在您的工程中添加上述两个依赖，如果是开发文档描述错误，请在下面留下文档地址，我们会通知文档中心更新此文档。
