### ISSUE TITLE
android里没用javax.xml.bind.DatatypeConverter

### ISSUE THREAD

**Issue by MDZ2** [aliyun/aliyun-openapi-java-sdk#30]
因为这个HmacSHA1Signer.java导入了javax.xml.bind.DatatypeConverter.
所以没法在android中使用,实在是不知道怎么弄了.
应该是android库中没有一些可以用的库吧,希望可以改下调用啥的,兼容下android(　ﾟ 3ﾟ)
我想弄个一键新建ecs服务器的应用来方便我挂代理玩游戏,按量计费每次手动配置太麻烦了.

**Comment by conan425** [comment]
@MDZ2 感谢您关注阿里云Java SDK，您的反馈已经收到，这个问题在我们的计划中，敬请期待！

**Comment by 42thcoder** [comment]
过去半年了，有啥进展么

**Comment by huajunsu** [comment]
同样的问题，在android里面这个sdk用不了啊，那个版本能解决？

**Comment by interkenny** [comment]
> Attempt to invoke interface method 'java.lang.String javax.xml.bind.DatatypeConverterInterface.printBase64Binary(byte[])' on a null object reference
>         at javax.xml.bind.DatatypeConverter.printBase64Binary(DatatypeConverter.java:547)
有什么 办法？

**Comment by ssy352959096** [comment]
您好，建议您先升级jdk至1.8以上，如果问题没有解决，您可以再次联系我们，祝您生活愉快！
