### ISSUE TITLE
redis sdk缺少接口

### ISSUE THREAD

**Issue by bringyou** [aliyun/aliyun-openapi-java-sdk#306]
云redis的[DescribePrice](https://help.aliyun.com/document_detail/95612.html?spm=a2c4g.11186623.2.45.78997c0cO9dcCB)接口，在2.1.1版本的sdk中没有对应的接口

**Comment by atptro** [comment]
在新的版本中，产品把DescribePrice设为private属性了，如果有需要可以去rds 提工单询问
