### ISSUE TITLE
rds sdk缺少文档

### ISSUE THREAD

**Issue by bringyou** [aliyun/aliyun-openapi-java-sdk#307]
目前最新的rds sdk中有[DescribePriceReqest](https://github.com/aliyun/aliyun-openapi-java-sdk/blob/master/aliyun-java-sdk-rds/src/main/java/com/aliyuncs/rds/model/v20140815/DescribePriceRequest.java)接口，但是并没有相关的[文档](https://help.aliyun.com/document_detail/26226.html)，希望能进行补充

**Comment by atptro** [comment]
在新的版本中，产品把DescribePrice设为private属性了，如果有需要可以去rds 提工单询问
