### ISSUE TITLE
dds sdk缺失文档

### ISSUE THREAD

**Issue by bringyou** [aliyun/aliyun-openapi-java-sdk#308]
dds sdk(mongodb) 中的[DescribeRenewalPriceRequest](https://github.com/aliyun/aliyun-openapi-java-sdk/blob/master/aliyun-java-sdk-dds/src/main/java/com/aliyuncs/dds/model/v20151201/DescribeRenewalPriceRequest.java)缺少对应的文档，希望能够补全。  
另外，如果能提供类似的DescribePriceRequest接口就更好了

**Comment by atptro** [comment]
https://help.aliyun.com/document_detail/132060.html?spm=5176.10695662.1996646101.searchclickresult.465d4621bTti4c&aly_as=pBFqqBO
您好这个是DescribeRenewalPrice接口的文档
