### ISSUE TITLE
r_kvstore.DescribeInstancesResponse.KVStoreInstance.HasRenewChangeOrder 类型不匹配

### ISSUE THREAD

**Issue by morlay** [aliyun/aliyun-openapi-java-sdk#31]
![image](https://user-images.githubusercontent.com/1667873/34290554-0ca98a5c-e733-11e7-9591-25051c24e549.png)

定义为 String 但 JSON 返回为 Boolean

**Comment by ElaineFei** [comment]
您好，虽然您是使用SDK时遇到该问题，但是该问题属于产品方文档和实际输出不相符合，我这边会反馈到产品，必要的话您也可以自己联系产品方。

**Comment by morlay** [comment]
产品文档并没有此字段。
而根据语义，这里确实应该为 Boolean，SDK 需要做相应更改吧。

**Comment by ElaineFei** [comment]
您好，该问题属于产品方文档和接口问题，我们已经联系了产品方。麻烦您加钉钉群 11771185 沟通更方便，便于我们找产品方同学支持问题。还请理解，谢谢。

**Comment by gaort** [comment]
@morlay 
这块的确是产品分文档、接口、实际返回不一致的问题
SDK中的字段类型，是根据产品方提供给SDK的API接口定义来生成的，因为这个API中，字段配置是string，所以生成的SDK就是String类型了。
我们已将本问题反馈给相关同事，但是接口的修改可能还需要时间，在这之前，你可以使用client.doAction()来获得反序列化之前的应答。
类似的问题，您也可以直接提交工单，可以得到更快的响应和解决。
