### ISSUE TITLE
slb.DescribeLoadBalancerAttributeResponse.listenerPorts 定义与文档及实际返回不符合，以至返回解析失败

### ISSUE THREAD

**Issue by morlay** [aliyun/aliyun-openapi-java-sdk#32]
文档：https://help.aliyun.com/document_detail/27583.html?spm=5176.doc27583.6.636.0AqIsi 

https://github.com/aliyun/aliyun-openapi-java-sdk/blob/master/aliyun-java-sdk-slb/src/main/java/com/aliyuncs/slb/model/v20140515/DescribeLoadBalancerAttributeResponse.java#L84 此处应为 `List<Integer>`

**Comment by ElaineFei** [comment]
您好，您的问题我们会反馈给SLB产品团队，若有回复我将尽快同步您。您也可以自行提工单咨询。

**Comment by gaort** [comment]
@morlay 
您好，相关问题我们已经反馈给SLB团队
这块的修改可能需要些时间，在这之前，您可以使用client.doAction()来获取反序列化之前的应答，以绕过反序列化错误。
