### ISSUE TITLE
Java SDK ECS: Wrong endpoint URLs are generated

### ISSUE THREAD

**Issue by arafato** [aliyun/aliyun-openapi-java-sdk#322]
Hi--, 

### SDK Version
```
// https://mvnrepository.com/artifact/com.aliyun/aliyun-java-sdk-core
    compile group: 'com.aliyun', name: 'aliyun-java-sdk-core', version: '4.4.4'
// https://mvnrepository.com/artifact/com.aliyun/aliyun-java-sdk-ecs
   compile group: 'com.aliyun', name: 'aliyun-java-sdk-ecs', version: '4.17.4'
```
### Code
Please see https://github.com/aliyun/aliyun-openapi-java-sdk#quick-examples for reproduction code.

### Error
```
com.aliyuncs.exceptions.ClientException: SDK.ServerUnreachable : 
Server unreachable: connection http://ecs.cn-hangzhou.aliyuncs.com/?
Action=DescribeInstances&PageSize=100&Timestamp=2019-09-10T11%3A48%3A23Z&InstanceName=xxx&SignatureVersion=1.0
&ServiceCode=ecs&Format=JSON
&SignatureNonce=cc2d6b17-8a77-4031-a527-8f0282aeb835156811610*****
&Version=2014-05-26&AccessKeyId=****&Signature=%2Bsbxd1GIrz6****%3D&SignatureMethod=HMAC-SHA1&RegionId=cn-hangzhou failed
```

It seems that the endpoint URL is not generated correctly:

For region = cn-hangzhou the code makes a request against `http://ecs.cn-hangzhou.aliyuncs.com` instead of `http://ecs-cn-hangzhou.aliyuncs.com`. This is also true for other regions such as cn-shenzhen.

**Comment by JacksonTian** [comment]
Please upgrade aliyun-openapi-java-core and aliyun-openapi-java-ecs to latest version. Thanks.

**Comment by arafato** [comment]
So 4.4.4 and 4.17.4 are not the latest releases?

**Comment by JacksonTian** [comment]
<img width="1053" alt="屏幕快照 2019-09-11 下午12 38 44" src="https://user-images.githubusercontent.com/327019/64674706-0085bb00-d4a4-11e9-9712-e2a04acd66f7.png">

Please use `export DEBUG=sdk` environment variable. And run it again. Like above.

**Comment by arafato** [comment]
They are using the latest version in Maven repository. Can you update the maven repo? I'll send you the debug output soon.

**Comment by JacksonTian** [comment]
@arafato How about your debug output?

**Comment by JacksonTian** [comment]
I used the latest version  of core/ecs from maven repo.

**Comment by JacksonTian** [comment]
Hi @arafato I am sorry for this issue. The problem is 'cn-hangzhou' == new String('cn-hangzhou'). We fixed it in 4.4.5. Please upgrade aliyun-java-sdk-core to 4.4.5 to avoid it again.

Thank you for report this issue.

**Comment by arafato** [comment]
Thanks a lot @JacksonTian ! Will notify customer.

**Comment by JacksonTian** [comment]
I closed the issue. If any questions, feel free to re-open it.
