### ISSUE TITLE
类 CreateClusterRequest 不具有设置参数的方法，然后导致无法向请求中添加参数

### ISSUE THREAD

**Issue by jliu666** [aliyun/aliyun-openapi-java-sdk#34]
类 CreateClusterRequest 不具有设置参数的方法，然后导致无法向请求中添加参数，如题

**Comment by gaort** [comment]
@jliu666 请问您说的CreateClusterRequest具体的package是什么？

**Comment by gaort** [comment]
@jliu666 
因为没能得到您的回复，我们先暂时关闭此issue了。
目前的确有部分产品的Request是无法设置相关参数的，这种情况，建议您使用CommonAPI泛化调用接口。
您可以在 https://help.aliyun.com/document_detail/61469.html 得到具体的使用方法

**Comment by jliu666** [comment]
https://github.com/aliyun/aliyun-openapi-java-sdk/blob/master/aliyun-java-sdk-cs/src/main/java/com/aliyuncs/cs/model/v20151215/CreateClusterRequest.java
这个类
CommonAPI能自动判断url和content-type吗？
要是都像ossClient好用就行了 @gaort

**Comment by gaort** [comment]
@jliu666 
十分感谢您的反馈！
目前容器服务因为缺失api相关定义，所以自动生成的sdk不够友好，建议您参照api文档使用commonApi的调用方式
CommonApi是需要您手动指定域名和每个接口的url的，content-type会自动判断，您也可以手动指定。
我们会尽快与容器服务团队进行沟通，尽快推动这个问题
