### ISSUE TITLE
Suggestion: Generate thumbnail image when use IMM conversion doc to vector format

### ISSUE THREAD

**Issue by iamjimmylu** [aliyun/aliyun-openapi-java-sdk#350]
When use IMM CreateOfficeConversionTask to convert a document to vector format, there's no thumbnail image generated. In most cases, we need such a thumbnail for the purpose to preview the document in a list page. For now, I have to call the API twice to generate both vector and jpg format, and use the first page of the jpg for preview, and use the vector for the formal reading page. If the vector call can generate a thumbnail for a specified page, that will be great.

**Comment by JacksonTian** [comment]
Hi @iamjimmylu , The issue that you described need product part to support it. Would you submit a work order at Alibaba Cloud website?

**Comment by atptro** [comment]
Since there was no reply for a long time, we need to close this issue
