### ISSUE TITLE
The filename or extension is too long.

### ISSUE THREAD

**Issue by gzuhlwang** [aliyun/aliyun-openapi-java-sdk#36]
go build github.com/aliyun/alibaba-cloud-sdk-go/services/ecs: G:\go\pkg\tool\windows_amd64\compile.exe: fork/exec G:\go\pkg\tool\windows_amd64\compile.exe: The filename or extension is too long.

如何解决？

**Comment by gaort** [comment]
@gzuhlwang GO sdk相关问题请移步
https://github.com/aliyun/alibaba-cloud-sdk-go
请问目前问题解决了吗？
