### ISSUE TITLE
KeyPairCredentials (AK 2.0) won't work if my region is non-Japan region?

### ISSUE THREAD

**Issue by eneim** [aliyun/aliyun-openapi-java-sdk#39]
Below is my code, where AkBaseBuilder will build the Client request using the below constructor:

```java
// clientBuilder = new AkBaseBuilder("us-west-1"); <-- Doesn't work, throw com.aliyuncs.exceptions.ServerException: InternalError
clientBuilder = new AkBaseBuilder("ap-northeast-1"); <-- This works
```

AkBaseBuilder.java

```java
/** ClientBuilder: an interface to help build an IAcsClient, make it compatible with old way of using key/secret. */
public class AkBaseBuilder implements ClientBuilder {

  private final IClientProfile profile;
  private final KeyPairCredentials credentials;

  public AkBaseBuilder(String regionId) throws IOException {
    InputStream privateKey =
        AkBaseBuilder.class.getClassLoader().getResourceAsStream("private_key.pem");
    this.profile = DefaultProfile.getProfile(regionId);
    this.credentials = new KeyPairCredentials("<myPublicKeyId>", read(privateKey));
  }

  private static String read(InputStream input) throws IOException {
    try (BufferedReader buffer = new BufferedReader(new InputStreamReader(input))) {
      return buffer.lines().collect(Collectors.joining("\n"));
    }
  }

  @Override public IAcsClient build() {
    STSGetSessionAccessKeyCredentialsProvider credentialsProvider =
        new STSGetSessionAccessKeyCredentialsProvider(credentials, profile);
    return new DefaultAcsClient(profile, credentialsProvider);
  }
}
```

I want to have my client to flexibly switch between Japan and US for scalability. Also using AK2.0 is super useful, but it seems that the client always failed to make the request to non-Japan region (like US as above). Please help to tell if I'm doing anything wrong or how it can be fixed? 

I'm using sdk-core 3.5.1, java 8 sdk. Thanks in advance.

**Comment by gaort** [comment]
@eneim 
Thanks for your feedback, your codes is no problem，
it's because currently only Japan regions support RsaKeyPairCredentials verification

**Comment by eneim** [comment]
@gaort Got it. Can I know if there is a plan to support other regions? At least US regions? I would like to use the same code base as we don't have much resource for maintain various versions. Thanks.

**Comment by gaort** [comment]
@eneim
We asked the relevant colleague for you. 
The reply received was “there's no plan to support the US regions in the short term”
Sorry for that.
You can report this requirement to the sts/ram team by submitting a new ticket
