### ISSUE TITLE
Missing parameter VSwitchName in DescribeVSwitchesRequest

### ISSUE THREAD

**Issue by pimuzzo** [aliyun/aliyun-openapi-java-sdk#397]
Using Java SDK we found out that in the class `DescribeVSwitchesRequest` is missing the parameter to filter the vSwitches by name.
The operation seems to be possible via [API](https://www.alibabacloud.com/help/doc-detail/35748.htm) using the parameter VSwitchName.

Here our versions:
```
<!-- https://mvnrepository.com/artifact/com.aliyun/aliyun-java-sdk-core -->
<dependency>
	<groupId>com.aliyun</groupId>
	<artifactId>aliyun-java-sdk-core</artifactId>
	<version>4.5.0</version>
</dependency>
<!-- https://mvnrepository.com/artifact/com.aliyun/aliyun-java-sdk-ecs-->
<dependency>
	<groupId>com.aliyun</groupId>
	<artifactId>aliyun-java-sdk-ecs</artifactId>
	<version>4.18.3</version>
</dependency>
```

**Comment by atptro** [comment]
The issue that you described need product part to support it. Would you submit a work order at Alibaba Cloud website?
