### ISSUE TITLE
IoT 发布广播消息的疑惑

### ISSUE THREAD

**Issue by dongkuo** [aliyun/aliyun-openapi-java-sdk#40]
我现在在IoT控制台创建了一个产品，假设productKey为252FUPqSxj2vXXX，该产品下有一个设备（deviceName为test_device）订阅了Topic：/252FUPqSxj2vXXX/test_device/get；我现在调用发布广播消息接口，并设置TopicFullName参数为：/broadcast/252FUPqSxj2vXXX/get，但设备并没有收到订阅消息。应该是我用法错了，能再解释一下这个接口么？

**Comment by jxyowen** [comment]
建议工单咨询相关产品
