### ISSUE TITLE
建议：添加返回值基类

### ISSUE THREAD

**Issue by ChinaLym** [aliyun/aliyun-openapi-java-sdk#400]
以 dysmsapi 为例
        private String requestId;
	private String signName;
	private String code;
	private String message;

这四个字段所有返回值里有，为什么不添加一个共同的基类？

即不影响兼容性，又方便使用者统一处理返回值

**Comment by atptro** [comment]
sdk 是面向阿里云所有产品的不会只面向dysmsapi，其他产品里面不一定有signName这些字段所以不会添加基类
