### ISSUE TITLE
aliyun cloud api 有没有swagger或openapi定义文件？

### ISSUE THREAD

**Issue by chen56** [aliyun/aliyun-openapi-java-sdk#413]
aliyun cloud api 有没有swagger或openapi定义文件？

类似[openapi](https://github.com/OAI/OpenAPI-Specification) 的api 定义文件?
如果有的话，大家使用起来就很方便了

**Comment by songshenzong** [comment]
> aliyun cloud api 有没有swagger或openapi定义文件？
> 
> 类似[openapi](https://github.com/OAI/OpenAPI-Specification) 的api 定义文件?
> 如果有的话，大家使用起来就很方便了

会有，到时在这回复您。

**Comment by JacksonTian** [comment]
@chen56 API 网关本身支持导出 swagger。不知道您是否要的是这个功能。

**Comment by chen56** [comment]
@JacksonTian 是指阿里云自己的云api 有没有swagger, 不是api网关

**Comment by JacksonTian** [comment]
@chen56 阿里云自己的 API 没有 Swagger，因为它的风格不是 RESTful 的。我们后面会给出另外一种格式的描述定义。
