### ISSUE TITLE
对接了短信推送和邮件推送，分别是不同的Region、AccessKey。可共用同一个IAcsClient对象吗

### ISSUE THREAD

**Issue by ak78** [aliyun/aliyun-openapi-java-sdk#415]
JAVA语言，同一项目中接入了短信推送和邮件推送，然后这两个服务分别是不同的两个平台账号和Region（cn-hangzhou、cn-shenzhen）。
问题1：采用sping Bean实例化IAcsClient后，两个服务都可以引用IAcsClient吗？
问题2： DefaultProfile.addEndpoint 怎么设置两个Region和两个推送服务？

**Comment by atptro** [comment]
实例化两个client，每种产品用一个
