### ISSUE TITLE
短信服务回调需要的包居然还是jar包 而且还没有maven版本 差评

### ISSUE THREAD

**Issue by zhangruhong** [aliyun/aliyun-openapi-java-sdk#45]
SDK及DEMO下载_SDK及DEMO下载_开发指南_短信服务-阿里云
https://help.aliyun.com/document_detail/55359.html?spm=a2c4g.11186623.4.1.J2Yppv

**Comment by zhangruhong** [comment]
我感觉你们是不是在原始社会

**Comment by jxyowen** [comment]
您好，文档中写着可以从maven下载，https://mvnrepository.com/search?q=aliyun-java-sdk-dysmsapi
