### ISSUE TITLE
NAT無法取得SnatTableIds

### ISSUE THREAD

**Issue by sleep-dragon** [aliyun/aliyun-openapi-java-sdk#46]
在DescribeNatGatewaysResponse 並沒有出現取得 SnatTableIds 該參數的方法

https://help.aliyun.com/document_detail/36054.html?spm=a2c4g.11186623.6.654.TfLat4

**Comment by Qingtang-SDK** [comment]
你好，已经联系相关同学查看，请稍等

**Comment by ssy352959096** [comment]
您好,问题已经解决了吗? 这里需要您提供更多的信息,如果已经解决,稍后我们将关闭它.感谢您的支持和反馈!
