### ISSUE TITLE
aliyun-java-sdk-elasticsearch ListSearchLogResponse取不到值

### ISSUE THREAD

**Issue by helloChan** [aliyun/aliyun-openapi-java-sdk#479]
* **产品和接口**: aliyun-java-sdk-elasticsearch ListSearchLog
* **平台**: Elasticsearch
* **代码路径**:  
```
aliyun-openapi-java-sdk/aliyun-java-sdk-elasticsearch/src/main/java/com/aliyuncs/elasticsearch/transform/v20170613/ListSearchLogResponseUnmarshaller.java
```
* **最小代码**:
```
 resultItem.setLevel(context.stringValue("ListSearchLogResponse.Result[" + i + "].level"));
 resultItem.setContent(context.stringValue("ListSearchLogResponse.Result[" + i + "].content"));
```
* **实际响应数据结构**:  
```
{
    "Headers": {
        "X-Total-Count": 4
    },
    "RequestId": "DEF7CE8E-A744-4E25-BD45-*****",
    "Result": [
        {
            "contentCollection": {
                "content": "****** ",
                "host": "*****",
                "level": "trace",
                "time": "2020-09-23T18:06:53.966Z"
            },
            "host": "172.16.**.212",
            "instanceId": "*****",
            "timestamp": 1600855613966
        }
    ]
}
```

**Comment by atptro** [comment]
这个需要去提工单了，api返回数据和定义不符合

**Comment by helloChan** [comment]
可以拉分支修改吗，然后你们通过了，更新一下SDK



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aliyun/aliyun-openapi-java-sdk"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月24日(星期四) 晚上6:11
收件人:&nbsp;"aliyun/aliyun-openapi-java-sdk"<aliyun-openapi-java-sdk@noreply.github.com&gt;;
抄送:&nbsp;"程序框"<284910889@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [aliyun/aliyun-openapi-java-sdk] aliyun-java-sdk-elasticsearch ListSearchLogResponse取不到值 (#479)





 
这个需要去提工单了，api返回数据和定义不符合

**Comment by atptro** [comment]
sdk的代码都是生成的，手动修改没有意义，如果elasticsearch 返回结构没有修改，下次自动发布还会是错的
