### ISSUE TITLE
云市场按量数据推送接口持续返回 500 错误

### ISSUE THREAD

**Issue by sevensees** [aliyun/aliyun-openapi-java-sdk#48]
按照[按量数据推送接口](https://help.aliyun.com/document_detail/51494.html?spm=5176.11065259.1996646101.searchclickresult.26c7666bs1737K)的样例，尝试推送数据之后，会持续返回 `500` 错误，其中 instanceId 是真实的 ID。

请教一下，导致这个错误的原因有哪些呢？

另外，我看到样例里面 `endpoint` 和 `regionId` 都是 `cn-hangzhou1`，想请教一下这两个的定义是什么，有没有可取指的列表？

**Comment by jxyowen** [comment]
您好，业务问题建议查看官方文档说明，如果没有解决问题，请工单咨询
