### ISSUE TITLE
是否支持android呢

### ISSUE THREAD

**Issue by crazysniper** [aliyun/aliyun-openapi-java-sdk#510]
android里面使用人脸识别的时候，会报这个
java.lang.NoSuchFieldError: No static field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar!classes3.dex)

请问要如何解决

**Comment by JacksonTian** [comment]
亲，可以使用这个： https://github.com/aliyun/alibabacloud-sdk/tree/master/facebody-20191230/java
