### ISSUE TITLE
正式代码中有控制台输出

### ISSUE THREAD

**Issue by nickwongwong** [aliyun/aliyun-openapi-java-sdk#52]
https://github.com/aliyun/aliyun-openapi-java-sdk/blob/bf5acabbd0dff2c84eba246ae53c25fdb108a017/aliyun-java-sdk-core/src/main/java/com/aliyuncs/regions/DescribeEndpointServiceImpl.java#L62
正式代码有System.out.println

**Comment by Qingtang-SDK** [comment]
感谢你的反馈，在最新的代码中已经解决了这个问题。
