### ISSUE TITLE
是否考虑支持万网(www.net.cn)的虚拟主机？

### ISSUE THREAD

**Issue by renfei** [aliyun/aliyun-openapi-java-sdk#544]
您好！
我在帮助中心寻找了一圈并没有找到关于万网虚拟主机的SDK支持， 官方是否考虑支持万网的虚拟主机呢。

## 我的需求场景是这样的

由于我使用 Let's Encrypt 的SSL证书，每三个月就需要重新签发一次。
这就需要程序自动续订证书并部署证书，云服务上利用SDK可以很好的完成。
但遇到万网虚拟主机，我就不知道如何自动化更新证书了，目前我能想到的只能是套用CDN，在CDN上做 https，所以，开发团队是否考虑支持万网(netcn)的虚拟主机？

## 另外吐槽一下虚拟主机

如下图所见，虚拟主机的域名只能在绑定时选择SSL证书，一旦绑定好，只能先关闭再打开HTTPS的时候选择SSL证书，就不能直接修改吗。
![image](https://user-images.githubusercontent.com/6532952/107667017-1ff0cb00-6cca-11eb-9896-9f7c0d62e74c.png)

![image](https://user-images.githubusercontent.com/6532952/107668041-2f244880-6ccb-11eb-8976-a0ef5de58667.png)

**Comment by JacksonTian** [comment]
亲，请提交下工单。
