### ISSUE TITLE
maven 无法下载 aliyun-java-sdk-core 4.0.6 以上版本

### ISSUE THREAD

**Issue by AlfnXd** [aliyun/aliyun-openapi-java-sdk#58]
\<=4.0.6:

![image](https://user-images.githubusercontent.com/8044101/46900689-c3522b00-ced8-11e8-933b-1411fc5501fd.png)

![image](https://user-images.githubusercontent.com/8044101/46900622-a23d0a80-ced7-11e8-93be-c554016db8e9.png)

\> 4.0.6

![image](https://user-images.githubusercontent.com/8044101/46900635-c7317d80-ced7-11e8-86cf-c81a5f27b392.png)

![image](https://user-images.githubusercontent.com/8044101/46900667-825a1680-ced8-11e8-86d8-314b06dae326.png)

仓库配置：

```
<repositories> 
  <repository> 
    <id>alimaven</id>  
    <name>aliyun maven</name>  
    <url>https://maven.aliyun.com/repository/public</url>  
    <releases> 
      <enabled>true</enabled> 
    </releases>  
    <snapshots> 
      <enabled>false</enabled> 
    </snapshots> 
  </repository> 
</repositories>
```

是我的配置有问题吗？

**Comment by atptro** [comment]
在maven的setting文件里面设置阿里公共仓库可以下载最新的版本
<mirror>
        <id>aliMaven</id>
        <mirrorOf>*</mirrorOf>
        <name>aliyunMaven</name>
        <url>http://maven.aliyun.com/nexus/content/groups/public</url>
    </mirror>

**Comment by atptro** [comment]
`<mirror>
        <id>aliMaven</id>
        <mirrorOf>*</mirrorOf>
        <name>aliyunMaven</name>
        <url>http://maven.aliyun.com/nexus/content/groups/public</url>
    </mirror> `

**Comment by JacksonTian** [comment]
@AlfnXd 请用上面的配置进行安装。
