### ISSUE TITLE
专有云Apsara Stack SDK不存在的问题

### ISSUE THREAD

**Issue by Chrisxuan** [aliyun/aliyun-openapi-java-sdk#62]
专有云企业版开发指南中提及的SignatureHelper类，未找到相对应的sdk

**Comment by Qingtang-SDK** [comment]
请问你说的是这个文档吗？ https://apsarastackdocument.oss-cn-hangzhou.aliyuncs.com/01_ApsaraStackEnterprise/V3.5.2-zh-cn/%E9%98%BF%E9%87%8C%E4%BA%91%20%E4%B8%93%E6%9C%89%E4%BA%91%E4%BC%81%E4%B8%9A%E7%89%88%20V3.5.2%20%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97%20-%2020180831.pdf

**Comment by Chrisxuan** [comment]
@Qingtang-SDK 请问在哪里找的到呢

**Comment by ssy352959096** [comment]
您好，感谢您对我们的支持，我们会在下个版本的文档中优化相关描述，届时如果问题没有得到解决，您可以重新打开这个问题。祝您生活愉快！

**Comment by JacksonTian** [comment]
您好。专有云的 SDK 支持不在这个仓库中。如果您还有疑问，请在工单系统中提交工单。
