### ISSUE TITLE
How to Settings proxy in Api?

### ISSUE THREAD

**Issue by yy1111-yang** [aliyun/aliyun-openapi-java-sdk#64]
How to Settings proxy in Api?

**Comment by atptro** [comment]
You can try the following method：
System.setProperty("http.proxyHost", "xxx.xxx.xxx.xxx");
System.setProperty("http.proxyPort", "xxxx");

**Comment by ssy352959096** [comment]
Has the problem been solved? We will close it later. If your problem is not resolved, you can open it again, thank you for your support and wish you a happy life!
