### ISSUE TITLE
aliyun-java-sdk-mts QueryMediaListByURLRequest的setFileURLs包含特殊字符时报错

### ISSUE THREAD

**Issue by wanglichao1** [aliyun/aliyun-openapi-java-sdk#65]
QueryMediaListByURLRequest request = new QueryMediaListByURLRequest();
		request.setFileURLs(“http://opensxbvideoy.oss-cn-beijing.aliyuncs.com/testuoriginal/face2face/resource/video/2345148M[电影天堂www.dygod.net].mov”);
报错：
com.aliyuncs.exceptions.ClientException: InvalidParameter.InvalidHTTPProtocol : The parameter  "InputFileUrl" is not a valid url,protocol not supported
RequestId : 97A4F6E0-9A0C-46BC-A5E4-52D887CFBBD6
	at com.aliyuncs.DefaultAcsClient.parseAcsResponse(DefaultAcsClient.java:225)
	at com.aliyuncs.DefaultAcsClient.getAcsResponse(DefaultAcsClient.java:134)
	at cn.com.open.aliyunoss.controller.MtsController.getTransUrlBySourceUrl(MtsController.java:73)

**Comment by atptro** [comment]
你好 这个问题我们会进行跟进

**Comment by ssy352959096** [comment]
您好，问题已经解决了吗？我们需要您提供一些信息去复现它，稍后我们将关闭这个问题，如果问题没有解决，您可以重新打开这个问题，感谢您的支持和反馈！

**Comment by wanglichao1** [comment]
只要请求的URL带有[]等特殊字符就有问题，只有中文是能成功的

**Comment by ssy352959096** [comment]
您好，请先升级core至最新版本4.3.4，如果问题没有解决，可以加下钉钉群23323247，方便解决问题，感谢您的反馈！

**Comment by ssy352959096** [comment]
@wanglichao1

**Comment by ssy352959096** [comment]
您好，复现问题后发现，是由产品方无法解析[]等特殊符号导致，已协助提交工单至相关产品，请您保持关注，感谢您的反馈！
