### ISSUE TITLE
InvalidDiskCategory.ZoneNotSupported

### ISSUE THREAD

**Issue by intesar** [aliyun/aliyun-openapi-java-sdk#7]
I'm seeing the following error. My code was working all of a sudden it started throwing this errors.
BTW - Niether SystemDisk nor DataDisk are set.

com.aliyuncs.exceptions.ClientException: InvalidDiskCategory.ZoneNotSupported : The specified zone does not support this disk category

**Comment by cbangyu-dev** [comment]
I got the same error: 'Code': 'InvalidDiskCategory.ZoneNotSupported', 'Message': 'The specified zone does not support this disk category.'

**Comment by ElaineFei** [comment]
Hello, I'm sorry, I was not able to reply your question in time. Next, Alibaba Cloud official technical staff will provide you with efficient support. If you still have questions that are not answered, please resubmit the issue. Thank you for your attention on Alibaba Cloud and Alibaba Cloud SDK.
