### ISSUE TITLE
有获取账号余额的sdk吗

### ISSUE THREAD

**Issue by wangchunfei** [aliyun/aliyun-openapi-java-sdk#73]
有获取账号余额的sdk吗。如果有的话，是哪个

**Comment by JacksonTian** [comment]
这个问题请提工单询问下有没有相关 OpenAPI。

**Comment by wangchunfei** [comment]
找到了，有个bssopenapi，里面有个QueryAccountBalanceRequest类可以用，没有文档介绍，根本不知道怎么用

**Comment by JacksonTian** [comment]
这里我先关掉。文档请你工单咨询。
