### ISSUE TITLE
发送邮件的regionId 填什么？

### ISSUE THREAD

**Issue by anysome** [aliyun/aliyun-openapi-java-sdk#8]
IClientProfile profile = DefaultProfile.getProfile("cn-hangzhou", accessKey, accessSecret);
填杭州可以发送成功，就是后台总有提示错误。也不说明下参数调用？

Invoke_Error, requestId:9D03AE06-25BD-449C-A0AD-5993EB556ABE; code:InvalidRegionId; MsgThe specified region does not exist.
2016-08-18 17:51:52.789  INFO 30736 --- [cTaskExecutor-1] mail sent to xxx@qq.com with envId: 77924358388

**Comment by wuling0412** [comment]
您好，您可以在阿里云官网上提交工单给对应的产品，他们会给你提供一个合适的版本，谢谢~

**Comment by ElaineFei** [comment]
您好，很抱歉当时没能及时回复您的问题，后续阿里云官方技术人员将为您提供高效的支持。若您仍有问题未能得到解答，请您重新提交issue。感谢您关注阿里云，关注阿里云 SDK。
