### ISSUE TITLE
请问图像识别Image Recognition的SDK在哪里？（或者maven路径）

### ISSUE THREAD

**Issue by leiq2005** [aliyun/aliyun-openapi-java-sdk#88]
谢谢！  网站找遍了没找到~~

**Comment by JacksonTian** [comment]
您好。图像识别 因为 API 风格不属于通用的 阿里云风格 因此没有自动生成维护起来。

如果有进一步的需要，我们会尝试提供，但这需要花一定的时间和精力。

**Comment by ssy352959096** [comment]
您好,感谢您的反馈和建议,我们会认真评估,稍后我们将关闭这个问题,如果您还有其他建议,可以再次打开这个问题. 祝您工作愉快!
