### ISSUE TITLE
您好，请教一下EDAS的api在这里吗

### ISSUE THREAD

**Issue by kk580kk** [aliyun/aliyun-openapi-java-sdk#9]

**Comment by skypacer210** [comment]
@kk580kk 你好！可以先参考下EDAS的用户手册，链接如下：
https://edas-public.oss-cn-hangzhou.aliyuncs.com/doc/ALIYUN_EDAS_USER_GUIDE.pdf

**Comment by kk580kk** [comment]
@skypacer210 您好，我这里需要的是edas的sdk，不过我已经从销售的技术支持手中拿到了。谢谢

**Comment by skypacer210** [comment]
@kk580kk 👌 客气了

**Comment by ElaineFei** [comment]
您好，很抱歉当时没能及时回复您的问题，后续阿里云官方技术人员将为您提供高效的支持。若您仍有问题未能得到解答，请您重新提交issue。感谢您关注阿里云，关注阿里云 SDK。
